### ISSUE TITLE
AttributeError: 'VGGSmall' object has no attribute '_initialize_weights'

### ISSUE THREAD

**Issue by hsalkhatib** [ContinualAI/continual-learning-baselines#22]
Hello Andrea - I am trying to run the Split_Tiny_ImageNet Experiment but it keep throwing back an error which it seems to be related to the "small_vgg" model.  

![image](https://user-images.githubusercontent.com/24516650/173193095-e5af0cda-55df-445c-8617-80efa7aed4fc.png)

**Comment by AndreaCossu** [comment]
Are you using a custom model or the default one present in the experiment [here](https://github.com/ContinualAI/continual-learning-baselines/blob/02449a2a887b2a7b45cd6a6c57a6c231e18b4934/experiments/split_tiny_imagenet/lwf.py#L22)? The experiment runs fine on my side.

**Comment by hsalkhatib** [comment]
Thanks for your response. 
I am using your scripts as-is, with no customization from my side. The error is coming from the "small_vgg.py" in the "models" folder. I ran it a couple of times and re-downloaded the files in case I did a change by mistake but still got the same error. Please check the attached snapshot. I put side by side the script I am using and the model file with markups.

![Screen Shot 2022-06-11 at 9 55 22 AM](https://user-images.githubusercontent.com/24516650/173236559-96b41dde-21de-43d5-bcae-eed60302cd93.png)

**Comment by AndreaCossu** [comment]
This is strange, the `_initialize_weights` method is available from the torchvision `VGG` which is sub-classed by our model. Using the latest version of the repo works for me.

Can you provide me with a script .py to reproduce the error?

**Comment by hsalkhatib** [comment]
Below is the script, my torchvision version = 0.12.0+cu113

`!pip install avalanche-lib==0.1.0`

`from experiments.split_tiny_imagenet import lwf_stinyimagenet  # select the experiment`

`custom_hyperparameters = {'seed':9000, 'cuda':-1, 'learning_rate':0.01, 'epochs':5}`

`result_lwf_sgd = lwf_stinyimagenet(custom_hyperparameters)`

`print(result_lwf_sgd)`

Sorry for the troubles and thanks for your support

**Comment by AndreaCossu** [comment]
It seems `torchvision` does not have the `_initialize_weights` method anymore from 0.12.0 (it was present in `0.11.0` by looking at the source code). The method has been moved inside the `__init__`, controlled by a `init_weights` parameter. I have adapted the code to work with both version. Can you try again and see if it works?

**Comment by hsalkhatib** [comment]
Thank you Andrea for the update... I tested it, and it's working fine now perfectly... I appreciate your support.
Congrats on the new release; I already got it installed :)
