### ISSUE TITLE
Reproduce Generative Replay results

### ISSUE THREAD

**Issue by travela** [ContinualAI/continual-learning-baselines#27]
The target results depend on the generator that is being used (as well as other factors, such as how much replay data is generated and whether the replay data is class-balanced or not).

[This paper](https://arxiv.org/abs/1812.09111) lists the various results for different generative models.

**Comment by AndreaCossu** [comment]
Hi @travela, what do you mean exactly? Are you referring to the results of a strategy present in this repository?

**Comment by travela** [comment]
Hi @AndreaCossu, I simply want to add the reproducibility tests for the generative replay strategy. The strategy already exists in Avalanche but not in this repo. 
I'm running the test locally right now and will push it in a few minutes.

**Comment by AndreaCossu** [comment]
I see, thank you! I think the best way to do it is to choose a reference paper and implement that exact experimental setup. If the results match then it is fine and we can merge it.

**Comment by travela** [comment]
@AndreaCossu I reproduced the results of the reference paper that I linked. Only for one type of generative model, namely a VAE. Maybe you can have a look and see if you want to merge it. :)
