### ISSUE TITLE
update cope results

### ISSUE THREAD

**Issue by AntonioCarta** [ContinualAI/continual-learning-baselines#39]
@AndreaCossu can you update CoPE with the new results? @AlbinSou fixed it in his [last PR](https://github.com/ContinualAI/avalanche/pull/1285).

**Comment by AndreaCossu** [comment]
icarl updated in [this commit](https://github.com/ContinualAI/continual-learning-baselines/commit/444c2cab94c686a11975cf83f9a23abf21da12e1)

**Comment by AntonioCarta** [comment]
Did you update iCaRL or CoPE?

**Comment by AndreaCossu** [comment]
As it turns out, both of them :sweat_smile: thanks, cope has been updated in [this commit](https://github.com/ContinualAI/continual-learning-baselines/commit/a4a32b8d44175d7a06d74acd5e52a5fb2b397c0e)
