### ISSUE TITLE
Question about Synaptic intelligence baseline on the SplitMNIST dataset

### ISSUE THREAD

**Issue by vmromero-ubi** [ContinualAI/continual-learning-baselines#66]
First off, I would like to express my gratitude for creating this repository on continual learning baseline and the well put avalanche library. I am currently studying synaptic intelligence and trying to replicate the results, particularly on the SplitMNIST dataset. The page reports 97% accuracy which is described as the average accuracy across all experience after training on the last experience. However, when I run the code, the final accuracy is only 19.27%, which is exactly the same as when I manually evaluate the performance of the trained model against the full MNIST test dataset. Is the 19.27% accuracy correct? Or am I missing something?

All the best,

**Comment by AndreaCossu** [comment]
Hi @vmromero-ubi , Synaptic Intelligence requires a multi-headed model with task labels to reach 97% accuracy. In a class-incremental setup it will show complete forgetting (around 20% final accuracy)

**Comment by vmromero-ubi** [comment]
Hi @AndreaCossu , thank you very much for your response.
