### ISSUE TITLE
Reproduce Less-Forgetful Learning (LFL) results

### ISSUE THREAD

**Issue by AndreaCossu** [ContinualAI/continual-learning-baselines#8]
[link to the paper](https://www.aaai.org/ocs/index.php/AAAI/AAAI18/paper/view/17073)

**Comment by AntonioCarta** [comment]
we need to take this from Avalanche: [https://github.com/ContinualAI/avalanche/blob/master/examples/lfl_mnist.py](https://github.com/ContinualAI/avalanche/blob/master/examples/lfl_mnist.py)

**Comment by AndreaCossu** [comment]
Strategy added
